name: run_tests

on:
  push:
  pull_request:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 20
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pyomo numpy scipy pytest pybind11 gurobipy coverage idaes-pse
        idaes get-extensions
        pyomo download-extensions
        pyomo build-extensions
        pip install -e ./
    - name: run pytest
      run: |
        coverage run --source=. -m pytest -v ./
        coverage xml
        coverage report -m